### ISSUE TITLE
ArgumentError (argument out of range)

### ISSUE THREAD

**Issue by mrchucho** [ondrejbartas/sidekiq-cron#183]
After successfully executing **once**, sidekiq-cron is repeatedly raising an exception in sidekiq (and the sidekiq-cron web UI):

```
ArgumentError (argument out of range):
  /usr/share/ruby/2.3/time.rb:302:in `local'
  /usr/share/ruby/2.3/time.rb:302:in `make_time'
  /usr/share/ruby/2.3/time.rb:366:in `parse'
  sidekiq-cron (0.6.3) lib/sidekiq/cron/job.rb:276:in `initialize'
  sidekiq-cron (0.6.3) lib/sidekiq/cron/job.rb:214:in `new'
  sidekiq-cron (0.6.3) lib/sidekiq/cron/job.rb:214:in `block in all'
  sidekiq-cron (0.6.3) lib/sidekiq/cron/job.rb:212:in `collect'
  sidekiq-cron (0.6.3) lib/sidekiq/cron/job.rb:212:in `all'
  sidekiq-cron (0.6.3) lib/sidekiq/cron/web_extension.rb:13:in `block in registered'
  sidekiq (5.0.5) lib/sidekiq/web/application.rb:266:in `instance_exec'
  sidekiq (5.0.5) lib/sidekiq/web/application.rb:266:in `block in call'
  sidekiq (5.0.5) lib/sidekiq/web/application.rb:262:in `catch'
  sidekiq (5.0.5) lib/sidekiq/web/application.rb:262:in `call'
  rack-protection (2.0.0) lib/rack/protection/xss_header.rb:18:in `call'
  rack-protection (2.0.0) lib/rack/protection/base.rb:50:in `call'
  rack-protection (2.0.0) lib/rack/protection/base.rb:50:in `call'
  rack-protection (2.0.0) lib/rack/protection/path_traversal.rb:16:in `call'
  rack-protection (2.0.0) lib/rack/protection/json_csrf.rb:26:in `call'
  rack-protection (2.0.0) lib/rack/protection/base.rb:50:in `call'
  rack-protection (2.0.0) lib/rack/protection/base.rb:50:in `call'
  rack-protection (2.0.0) lib/rack/protection/frame_options.rb:31:in `call'
  rack-protection (2.0.0) lib/rack/protection/base.rb:50:in `call'
  rack (1.6.8) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.6.8) lib/rack/session/abstract/id.rb:220:in `call'
  rack (1.6.8) lib/rack/urlmap.rb:66:in `block in call'
  rack (1.6.8) lib/rack/urlmap.rb:50:in `each'
  rack (1.6.8) lib/rack/urlmap.rb:50:in `call'
  rack (1.6.8) lib/rack/builder.rb:153:in `call'
  sidekiq (5.0.5) lib/sidekiq/web.rb:103:in `call'
  sidekiq (5.0.5) lib/sidekiq/web.rb:108:in `call'
```

My scheduled is pretty simple (and the cron expression is valid):

```yaml
nightly_cleanup:
  cron: '0 5 * * *'
  class: NightlyCleanupWorker
  queue: default
```
```ruby
Rufus::Scheduler.parse('0 5 * * *').next_time
=> #<EtOrbi::EoTime:0x00000000056098e8 @seconds=1513918800.0, @zone=#<TZInfo::TimezoneProxy: Etc/UTC>, @time=2017-12-22 05:00:00 UTC>
```

I'm not sure if it has something to do with the fact that I'm using UTC on the host and in my Rails config. I'm running sidekiq-cron 0.6.3, sidekiq 5.0.5, Rails 4.2.10 and Ruby 2.3.5.

**Comment by mrchucho** [comment]
It looks like `last_enqueue_time` is failing to parse. Though my `last_enqueue_time` fails to parse in plain old Ruby...

```ruby
$ irb -rtime
2.3.5 :001 > Time.parse('12/19/2017')
ArgumentError: argument out of range
        from /home/vagrant/.rvm/rubies/ruby-2.3.5/lib/ruby/2.3.0/time.rb:302:in `local'
        from /home/vagrant/.rvm/rubies/ruby-2.3.5/lib/ruby/2.3.0/time.rb:302:in `make_time'
        from /home/vagrant/.rvm/rubies/ruby-2.3.5/lib/ruby/2.3.0/time.rb:366:in `parse'
```

**Comment by mrchucho** [comment]
If last enqueue time will always be a date in the format MM/DD/YYYY, then perhaps `strptime` would make more sense, e.g.

```ruby
@last_enqueue_time = Time.strptime(args['last_enqueue_time'], '%M/%d/%Y')
```
