### ISSUE TITLE
Web Ui not working for Sidekiq 5.4.0

### ISSUE THREAD

**Issue by inayabar** [ondrejbartas/sidekiq-cron#191]
Hi! Im trying to implement Sidekiq Cron in a Rails Api, but can't make the cron tab in Sidekiq web display. Im using:
  Sidekiq 5.4.0
  Rails 5.1.2
  Ruby 2.3.4p301

Im requiring sidekiq cron web inside routes.rb:
  require 'sidekiq/web'
  require 'sidekiq/cron/web'
  Sidekiq::Web.set :session_secret, Rails.application.secrets[:secret_key_base]
  mount Sidekiq::Web, at: 'sidekiq'

My gemfile looks like this:
  gem 'sidekiq'
  gem 'sidekiq-failures'
  gem 'sidekiq_mailer'
  gem 'sidekiq-unique-jobs'
  gem "sidekiq-cron", "~> 0.6.3"

Also, im using sidekiq-failures gem and that seems to add correctly the 'failures' tab. 

Any idea what could be wrong? Thanks in advance!

**Comment by ondrejbartas** [comment]
@inayabar Hi I have checked how sidekiq-failures are adding web extension and we do same thing.

So I don't know exactly what can be problem.

Can you please print in your routes under requires

`Sidekiq::Web.tabs`

what are the keys?

and if there is `{"Cron" => "cron"}` it should be displayed

**Comment by Geniekort** [comment]
Having the same problem, and `Sidekiq::Web.tabs` returns `{}`. Anyone found a solution yet?

**Comment by brunohkbx** [comment]
Any updates?

**Comment by mberlanda** [comment]
This looks be working with the following gemset:

```
    sidekiq (5.2.3)
      connection_pool (~> 2.2, >= 2.2.2)
      rack-protection (>= 1.5.0)
      redis (>= 3.3.5, < 5)
    sidekiq-cron (1.1.0)
      fugit (~> 1.1)
      sidekiq (>= 4.2.1)
    sidekiq-failures (1.0.0)
      sidekiq (>= 4.0.0)
    sidekiq-unique-jobs (6.0.12)
      concurrent-ruby (~> 1.0, >= 1.0.5)
      sidekiq (>= 4.0, < 7.0)
      thor (~> 0)
```

I am on ruby 2.5.3 and rails 5.2.2.

I guess this issue could be closed, isn't it @inayabar @Geniekort @brunohkbx ?

**Comment by mauri** [comment]
For what is worth, I'm getting the following error **intermittently**, even when invoking `rails console`

```
/Users/foo/.gem/ruby/2.5.3/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require': cannot load such file -- sidekiq/cron/web (LoadError)
	from /Users/foo/.gem/ruby/2.5.3/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
	from /Users/foo/.gem/ruby/2.5.3/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:80:in `register'
	from /Users/foo/.gem/ruby/2.5.3/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
	from /Users/foo/.gem/ruby/2.5.3/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:36:in `rescue in require'
	from /Users/foo/.gem/ruby/2.5.3/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:25:in `require'
	from /Users/foo/.gem/ruby/2.5.3/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `block in require'
	from /Users/foo/.gem/ruby/2.5.3/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:257:in `load_dependency'
	from /Users/foo/.gem/ruby/2.5.3/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `require'
	from /Users/foo/Workspace/myapp/config/routes.rb:33:in `block (2 levels) in <main>'
	from /Users/foo/.gem/ruby/2.5.3/gems/devise-4.6.0/lib/devise/rails/routes.rb:292:in `block in authenticate'
	from /Users/foo/.gem/ruby/2.5.3/gems/devise-4.6.0/lib/devise/rails/routes.rb:484:in `block in constraints_for'
	from /Users/foo/.gem/ruby/2.5.3/gems/actionpack-5.2.2/lib/action_dispatch/routing/mapper.rb:1008:in `block in constraints'
	from /Users/foo/.gem/ruby/2.5.3/gems/actionpack-5.2.2/lib/action_dispatch/routing/mapper.rb:879:in `scope'
	from /Users/foo/.gem/ruby/2.5.3/gems/actionpack-5.2.2/lib/action_dispatch/routing/mapper.rb:1008:in `constraints'
	from /Users/foo/.gem/ruby/2.5.3/gems/devise-4.6.0/lib/devise/rails/routes.rb:483:in `constraints_for'
	from /Users/foo/.gem/ruby/2.5.3/gems/devise-4.6.0/lib/devise/rails/routes.rb:291:in `authenticate'
	from /Users/foo/Workspace/myapp/config/routes.rb:30:in `block in <main>'
```

versions:
```
    sidekiq (5.2.5)
      connection_pool (~> 2.2, >= 2.2.2)
      rack (>= 1.5.0)
      rack-protection (>= 1.5.0)
      redis (>= 3.3.5, < 5)
    sidekiq-cron (1.1.0)
      fugit (~> 1.1)
      sidekiq (>= 4.2.1)
```

**Comment by mistaguy** [comment]
I had the same problem. When i checked remember me on login. The UI started to load properly
