### ISSUE TITLE
Invalid strptime format - '%Y-%m-%d %H:%M:%S'

### ISSUE THREAD

**Issue by rusllonrails** [ondrejbartas/sidekiq-cron#214]
Hey team :wave: 

Sidekiq-cron works fine in my application. :+1: 
But, noted strange issues on production environment:

```
2018-08-06T14:54:58.511Z 5 TID-1irzjp ERROR: invalid strptime format - `%Y-%m-%d %H:%M:%S'
/usr/local/bundle/gems/sidekiq-cron-1.0.0/lib/sidekiq/cron/job.rb:214:in `collect'
2018-08-06T14:54:58.511Z 5 TID-1irzjp WARN: ArgumentError: invalid strptime format - `%Y-%m-%d %H:%M:%S'
2018-08-06T14:54:58.512Z 5 TID-1irzjp WARN: /usr/local/lib/ruby/2.3.0/time.rb:429:in `strptime'
/usr/local/bundle/gems/sidekiq-cron-1.0.0/lib/sidekiq/cron/job.rb:278:in `initialize'
/usr/local/bundle/gems/sidekiq-5.1.3/lib/sidekiq/util.rb:25:in `block in safe_thread'
/usr/local/bundle/gems/sidekiq-cron-1.0.0/lib/sidekiq/cron/job.rb:216:in `block in all'
2018-08-06T14:54:58.511Z 5 TID-1irzjp ERROR: /usr/local/lib/ruby/2.3.0/time.rb:429:in `strptime'
/usr/local/bundle/gems/sidekiq-cron-1.0.0/lib/sidekiq/cron/job.rb:214:in `all'
/usr/local/bundle/gems/sidekiq-cron-1.0.0/lib/sidekiq/cron/poller.rb:14:in `enqueue'
/usr/local/bundle/gems/sidekiq-5.1.3/lib/sidekiq/scheduled.rb:68:in `block in start'
/usr/local/bundle/gems/sidekiq-5.1.3/lib/sidekiq/util.rb:16:in `watchdog'
/usr/local/bundle/gems/sidekiq-cron-1.0.0/lib/sidekiq/cron/job.rb:216:in `new'
```

**ENV:**

```
ruby (2.3.1)
rails (4.2.7.1)
sidekiq (5.1.3)
sidekiq-cron (1.0.0)
sidekiq-limit_fetch (3.0.1)
```

**config/initializers/sidekiq.rb**

```
# Needed in +5 version of Sidekiq
Sidekiq::Extensions.enable_delay!

 $redis = Redis.new(url: url)

  Sidekiq.configure_server do |config|
    config.redis = {
      url: ENV["REDIS_URL"],
      namespace: ENV["DOMAIN"]
    }
  end

  Sidekiq.configure_client do |config|
    config.redis = {
      url: ENV["REDIS_URL"],
      namespace: ENV["DOMAIN"]
    }
  end

  schedule_file = "config/schedule.staging.yml"

  Sidekiq.configure_server do |config|
    if File.exists?(schedule_file)
      Sidekiq::Cron::Job.load_from_hash YAML.load_file(schedule_file)
    end
  end
end
```

I guess issue can be caused here: 
https://github.com/ondrejbartas/sidekiq-cron/blob/master/lib/sidekiq/cron/job.rb#L278 
as I'm not using `strptime` in code related to sidekiq-cron tasks.

Maybe it's already fixed in next version / master branch?

Thanks for any help :beer:

**Comment by ondrejbartas** [comment]
@rusllonrails sorry for that, problem is that in v1.0.0 there was changes how we store times in redis (format) and this is why it stop working with upgrade. In v1.0.4 I added fallback for that so you should be able to normally upgrade without problem. Also You can remove all cron jobs from redis and then add them again, which will remove old time formats in redis.

**Comment by sanyam-j** [comment]
i am getting same issue with version v1.0.4

**Comment by jordanbrock** [comment]
I'm getting a similar error on this line:

https://github.com/ondrejbartas/sidekiq-cron/blob/master/lib/sidekiq/cron/job.rb#L590

I've tried deleting the jobs with Sidekiq::Cron::Job.delete_all! but the date format error breaks at the same place.

What's the best way to manually delete the jobs from redis?

**Comment by rusllonrails** [comment]
Thanks for response guys :beer: 
I will checkout 1.0.4 soon

**Comment by tomprats** [comment]
I'm getting this error too. To reproduce it, there just needs to be a cron job that has failed and be waiting in the retry queue. Then it looks like the timestamp is in the format `"08/11/2018  5:06 PM"`

**Comment by tomprats** [comment]
The reason the time is in that format is most likely related to having `Time::DATE_FORMATS[:default] = "%d/%m/%Y %l:%M %p"`. I tried to find a place where `Time.now.to_s` was being called versus `Time.now.to_f.to_s`, but couldn't

**Comment by jaredcwhite** [comment]
I was still getting an `ArgumentError: invalid date` all of a sudden even when upgrading to 1.2.0, so I add to execute the following in my console and restart in order to get things working again:

```ruby
job_hashes = nil
Sidekiq.redis do |conn|
  set_members = conn.smembers Sidekiq::Cron::Job.jobs_key
  job_hashes = conn.pipelined do
    set_members.each do |key|
      conn.hgetall(key)
    end
  end
end

job_hashes.each do |h|
  redis_key = Sidekiq::Cron::Job.redis_key(h['name'])
  job_enqueued_key = Sidekiq::Cron::Job.job_enqueued_key(h['name'])
  jid_history_key = Sidekiq::Cron::Job.jid_history_key(h['name'])

  Sidekiq.redis do |conn|
    #delete from set
    conn.srem Sidekiq::Cron::Job.jobs_key, redis_key

    #delete runned timestamps
    conn.del job_enqueued_key

    # delete jid_history
    conn.del jid_history_key

    #delete main job
    conn.del redis_key
  end
end
```
