### ISSUE TITLE
A copy of V1 has been removed from the module tree but is still active!

### ISSUE THREAD

**Issue by Yu-coding** [ondrejbartas/sidekiq-cron#253]
Hi @ondrejbartas , thanks for your supporting this gem!
I have made the cron job using sidekiq-cron gem.
But when I run sidekiq to start scheduling, I got this issue now.

```
2019-06-17T18:03:40.076Z 52960 TID-ox0sl27vc INFO: Booting Sidekiq 5.2.7 with redis options {:id=>"Sidekiq-server-PID-52960", :url=>nil}
A copy of V1 has been removed from the module tree but is still active!
/Users/admin/.rvm/gems/ruby-2.4.1/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:495:in `load_missing_constant'
/Users/admin/.rvm/gems/ruby-2.4.1/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/active_support.rb:60:in `block in load_missing_constant'
/Users/admin/.rvm/gems/ruby-2.4.1/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/active_support.rb:16:in `allow_bootsnap_retry'
/Users/admin/.rvm/gems/ruby-2.4.1/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/active_support.rb:59:in `load_missing_constant'
......
```

Could you please help to fix this issue?
Thank you.

**Comment by Yu-coding** [comment]
It was an issue in my helpers since I included helpers in sidekiq-cron worker.
I have fixed so now I close this issue.
