### ISSUE TITLE
undefined method `inject' for false:FalseClass

### ISSUE THREAD

**Issue by interpegasus** [ondrejbartas/sidekiq-cron#292]
Hi, I would like to know what might cause this error. It is triggered as soon as the code below is added to sidekiq.rb

**config/initializers/sidekiq.yml**
```
schedule_file = "config/schedule.yml"

if File.exist?(schedule_file) && Sidekiq.server?
  Sidekiq::Cron::Job.load_from_hash YAML.load_file(schedule_file)
end
```

**error**
```
RAILS_ENV=development bundle exec sidekiq
2020-08-11T00:04:22.491Z pid=5839 tid=outhh39bj INFO: Booting Sidekiq 6.0.7 with redis options {:url=>"redis://127.0.0.1/1", :network_timeout=>3}
undefined method `inject' for false:FalseClass
Did you mean?  inspect
/Users/sidekiquser/.rvm/gems/ruby-2.6.1/gems/sidekiq-cron-1.2.0/lib/sidekiq/cron/job.rb:153:in `load_from_hash'
/Users/sidekiquser/interpegasus/su-rye-acp-web-app/config/initializers/sidekiq.rb:23:in `<main>'
/Users/sidekiquser/.rvm/gems/ruby-2.6.1/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:55:in `load'
/Users/sidekiquser/.rvm/gems/ruby-2.6.1/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:55:in `load'
/Users/sidekiquser/.rvm/gems/ruby-2.6.1/gems/activesupport-6.0.3.2/lib/active_support/dependencies.rb:318:in `block in load'
/Users/sidekiquser/.rvm/gems/ruby-2.6.1/gems/activesupport-6.0.3.2/lib/active_support/dependencies.rb:291:in `load_dependency'
/Users/sidekiquser/.rvm/gems/ruby-2.6.1/gems/activesupport-6.0.3.2/lib/active_support/dependencies.rb:318:in `load'
/Users/sidekiquser/.rvm/gems/ruby-2.6.1/gems/railties-6.0.3.2/lib/rails/engine.rb:666:in `block in load_config_initializer'
/Users/sidekiquser/.rvm/gems/ruby-2.6.1/gems/activesupport-6.0.3.2/lib/active_support/notifications.rb:182:in `instrument'
/Users/sidekiquser/.rvm/gems/ruby-2.6.1/gems/railties-6.0.3.2/lib/rails/engine.rb:665:in `load_config_initializer'
/Users/sidekiquser/.rvm/gems/ruby-2.6.1/gems/railties-6.0.3.2/lib/rails/engine.rb:625:in `block (2 levels) in <class:Engine>'
/Users/sidekiquser/.rvm/gems/ruby-2.6.1/gems/railties-6.0.3.2/lib/rails/engine.rb:624:in `each'
/Users/sidekiquser/.rvm/gems/ruby-2.6.1/gems/railties-6.0.3.2/lib/rails/engine.rb:624:in `block in <class:Engine>'
/Users/sidekiquser/.rvm/gems/ruby-2.6.1/gems/railties-6.0.3.2/lib/rails/initializable.rb:32:in `instance_exec'
/Users/sidekiquser/.rvm/gems/ruby-2.6.1/gems/railties-6.0.3.2/lib/rails/initializable.rb:32:in `run'
/Users/sidekiquser/.rvm/gems/ruby-2.6.1/gems/railties-6.0.3.2/lib/rails/initializable.rb:61:in `block in run_initializers'
/Users/sidekiquser/.rvm/rubies/ruby-2.6.1/lib/ruby/2.6.0/tsort.rb:228:in `block in tsort_each'
/Users/sidekiquser/.rvm/rubies/ruby-2.6.1/lib/ruby/2.6.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
/Users/sidekiquser/.rvm/rubies/ruby-2.6.1/lib/ruby/2.6.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
/Users/sidekiquser/.rvm/rubies/ruby-2.6.1/lib/ruby/2.6.0/tsort.rb:431:in `each_strongly_connected_component_from'
/Users/sidekiquser/.rvm/rubies/ruby-2.6.1/lib/ruby/2.6.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
/Users/sidekiquser/.rvm/gems/ruby-2.6.1/gems/railties-6.0.3.2/lib/rails/initializable.rb:50:in `each'
/Users/sidekiquser/.rvm/gems/ruby-2.6.1/gems/railties-6.0.3.2/lib/rails/initializable.rb:50:in `tsort_each_child'
/Users/sidekiquser/.rvm/rubies/ruby-2.6.1/lib/ruby/2.6.0/tsort.rb:415:in `call'
/Users/sidekiquser/.rvm/rubies/ruby-2.6.1/lib/ruby/2.6.0/tsort.rb:415:in `each_strongly_connected_component_from'
/Users/sidekiquser/.rvm/rubies/ruby-2.6.1/lib/ruby/2.6.0/tsort.rb:349:in `block in each_strongly_connected_component'
/Users/sidekiquser/.rvm/rubies/ruby-2.6.1/lib/ruby/2.6.0/tsort.rb:347:in `each'
/Users/sidekiquser/.rvm/rubies/ruby-2.6.1/lib/ruby/2.6.0/tsort.rb:347:in `call'
/Users/sidekiquser/.rvm/rubies/ruby-2.6.1/lib/ruby/2.6.0/tsort.rb:347:in `each_strongly_connected_component'
/Users/sidekiquser/.rvm/rubies/ruby-2.6.1/lib/ruby/2.6.0/tsort.rb:226:in `tsort_each'
/Users/sidekiquser/.rvm/rubies/ruby-2.6.1/lib/ruby/2.6.0/tsort.rb:205:in `tsort_each'
/Users/sidekiquser/.rvm/gems/ruby-2.6.1/gems/railties-6.0.3.2/lib/rails/initializable.rb:60:in `run_initializers'
/Users/sidekiquser/.rvm/gems/ruby-2.6.1/gems/railties-6.0.3.2/lib/rails/application.rb:363:in `initialize!'
/Users/sidekiquser/interpegasus/su-rye-acp-web-app/config/environment.rb:5:in `<top (required)>'
/Users/sidekiquser/.rvm/gems/ruby-2.6.1/gems/activesupport-6.0.3.2/lib/active_support/dependencies.rb:324:in `require'
/Users/sidekiquser/.rvm/gems/ruby-2.6.1/gems/activesupport-6.0.3.2/lib/active_support/dependencies.rb:324:in `block in require'
/Users/sidekiquser/.rvm/gems/ruby-2.6.1/gems/activesupport-6.0.3.2/lib/active_support/dependencies.rb:291:in `load_dependency'
/Users/sidekiquser/.rvm/gems/ruby-2.6.1/gems/activesupport-6.0.3.2/lib/active_support/dependencies.rb:324:in `require'
/Users/sidekiquser/.rvm/gems/ruby-2.6.1/gems/sidekiq-6.0.7/lib/sidekiq/cli.rb:252:in `boot_system'
/Users/sidekiquser/.rvm/gems/ruby-2.6.1/gems/sidekiq-6.0.7/lib/sidekiq/cli.rb:37:in `run'
/Users/sidekiquser/.rvm/gems/ruby-2.6.1/gems/sidekiq-6.0.7/bin/sidekiq:31:in `<top (required)>'
/Users/sidekiquser/.rvm/gems/ruby-2.6.1/bin/sidekiq:23:in `load'
/Users/sidekiquser/.rvm/gems/ruby-2.6.1/bin/sidekiq:23:in `<main>'
/Users/sidekiquser/.rvm/gems/ruby-2.6.1/bin/ruby_executable_hooks:24:in `eval'
/Users/sidekiquser/.rvm/gems/ruby-2.6.1/bin/ruby_executable_hooks:24:in `<main>'
```

**rvm info**
```
$ rvm info

ruby-2.6.1:

  system:
    uname:        "Darwin sidekiqusers-MacBook.local 19.5.0 Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64 x86_64"
    name:         "OSX"
    version:      "10.15"
    architecture: "x86_64"
    bash:         "/bin/bash => GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin19)"
    zsh:          "/bin/zsh => zsh 5.7.1 (x86_64-apple-darwin19.0)"
    remote_path:  "osx/10.15/x86_64"
    xcode:        "11.6"

  rvm:
    version:      "1.29.10 (latest)"
    updated:      "21 days 9 hours 18 minutes ago"
    path:         "/Users/sidekiquser/.rvm"
    autolibs:     "[4] Allow RVM to use package manager if found, install missing dependencies, install package manager (only OS X)."

  ruby:
    interpreter:  "ruby"
    version:      "2.6.1p33"
    date:         "2019-01-30"
    platform:     "x86_64-darwin19"
    patchlevel:   "2019-01-30 revision 66950"
    full_version: "ruby 2.6.1p33 (2019-01-30 revision 66950) [x86_64-darwin19]"

  homes:
    gem:          "/Users/sidekiquser/.rvm/gems/ruby-2.6.1"
    ruby:         "/Users/sidekiquser/.rvm/rubies/ruby-2.6.1"

  binaries:
    ruby:         "/Users/sidekiquser/.rvm/rubies/ruby-2.6.1/bin/ruby"
    irb:          "/Users/sidekiquser/.rvm/rubies/ruby-2.6.1/bin/irb"
    gem:          "/Users/sidekiquser/.rvm/rubies/ruby-2.6.1/bin/gem"
    rake:         "/Users/sidekiquser/.rvm/gems/ruby-2.6.1/bin/rake"

  environment:
    PATH:         "/Users/sidekiquser/.rvm/gems/ruby-2.6.1/bin:/Users/sidekiquser/.rvm/gems/ruby-2.6.1@global/bin:/Users/sidekiquser/.rvm/rubies/ruby-2.6.1/bin:/Users/sidekiquser/.rvm/bin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/sidekiquser/.ebcli-virtual-env/executables:/usr/local/sbin:/flutter/bin:/Users/sidekiquser/interpegasus/su-rye-acp-web-app/flutter/bin"
    GEM_HOME:     "/Users/sidekiquser/.rvm/gems/ruby-2.6.1"
    GEM_PATH:     "/Users/sidekiquser/.rvm/gems/ruby-2.6.1:/Users/sidekiquser/.rvm/gems/ruby-2.6.1@global"
    MY_RUBY_HOME: "/Users/sidekiquser/.rvm/rubies/ruby-2.6.1"
    IRBRC:        "/Users/sidekiquser/.rvm/rubies/ruby-2.6.1/.irbrc"
    RUBYOPT:      ""
    gemset:       ""




```

Thanks

**Comment by interpegasus** [comment]
Just in case anyone find the same issue it was solved by validating the YAML file and ensuring the format is correct.
