### ISSUE TITLE
Sidekiq 6.5 Compatibility

### ISSUE THREAD

**Issue by jsantos** [ondrejbartas/sidekiq-cron#330]
Full backtrace:

```
/.../.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:15:in `require': cannot load such file -- sidekiq/util (LoadError)
from /.../.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:15:in `require'
from /.../.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-cron-1.4.0/lib/sidekiq/cron/job.rb:3:in `<top (required)>'
from /.../.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
from /.../.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
from /.../.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-cron-1.4.0/lib/sidekiq/cron.rb:1:in `<top (required)>'
from /.../.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
from /.../.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
from /.../.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-cron-1.4.0/lib/sidekiq-cron.rb:2:in `<top (required)>'
from /.../.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
from /.../.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
from /.../.rbenv/versions/3.1.2/lib/ruby/3.1.0/bundler/runtime.rb:60:in `block (2 levels) in require'
from /.../.rbenv/versions/3.1.2/lib/ruby/3.1.0/bundler/runtime.rb:55:in `each'
from /.../.rbenv/versions/3.1.2/lib/ruby/3.1.0/bundler/runtime.rb:55:in `block in require'
from /.../.rbenv/versions/3.1.2/lib/ruby/3.1.0/bundler/runtime.rb:44:in `each'
from /.../.rbenv/versions/3.1.2/lib/ruby/3.1.0/bundler/runtime.rb:44:in `require'
from /.../.rbenv/versions/3.1.2/lib/ruby/3.1.0/bundler.rb:176:in `require'
from /.../Documents/workspace/fms/config/application.rb:20:in `<top (required)>'
from /.../Documents/workspace/fms/config/environment.rb:2:in `require_relative'
from /.../Documents/workspace/fms/config/environment.rb:2:in `<top (required)>'
from /.../Documents/workspace/fms/test/test_helper.rb:22:in `require_relative'
from /.../Documents/workspace/fms/test/test_helper.rb:22:in `<main>'
from /.../.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
from /.../.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
from /.../Documents/workspace/fms/test/controllers/activations_controller_test.rb:1:in `<main>'
from /.../.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
from /.../.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
from /.../.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/railties-7.0.3/lib/rails/test_unit/runner.rb:47:in `block in load_tests'
from /.../.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/railties-7.0.3/lib/rails/test_unit/runner.rb:47:in `each'
from /.../.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/railties-7.0.3/lib/rails/test_unit/runner.rb:47:in `load_tests'
from /.../.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/railties-7.0.3/lib/rails/test_unit/runner.rb:40:in `run'
from /.../.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/railties-7.0.3/lib/rails/commands/test/test_command.rb:33:in `perform'
from /.../.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
from /.../.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
from /.../.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
from /.../.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/railties-7.0.3/lib/rails/command/base.rb:87:in `perform'
from /.../.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/railties-7.0.3/lib/rails/command.rb:48:in `invoke'
from /.../.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/railties-7.0.3/lib/rails/commands.rb:18:in `<main>'
from /.../.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
from /.../.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
from bin/rails:4:in `<main>'
```

Related: https://github.com/mperham/sidekiq/issues/5372

According to @mperham:

> "...sidekiq/util was an internal module and not a public API."

**Comment by markets** [comment]
Merged! A new release will be pushed to RubyGems in the following days.

In the meantime, you can point the gem to GitHub `master` branch: 

```ruby
gem 'sidekiq-cron', github: 'ondrejbartas/sidekiq-cron'
```

Sorry for any inconvenience. Thanks!

**Comment by markets** [comment]
New version `v1.5.0` released 🎉 

- https://rubygems.org/gems/sidekiq-cron/versions/1.5.0
- https://github.com/ondrejbartas/sidekiq-cron/releases/tag/v1.5.0
